import { useRef, useState } from 'react';
import { Upload, Users, X, Plus, Trash2, Download } from 'lucide-react';
import { DAYS } from './schedule';
import { validateTeachers, unknownCodes, type School, type Teacher } from './school';
type Pending={kind:'timetable';classes:School['classes'];filename:string}|{kind:'teachers';teachers:Teacher[];filename:string};
export function DataManager({school,onChange,disabled}:{school:School;onChange:(school:School)=>void;disabled:boolean}) {
 const dialog=useRef<HTMLDialogElement>(null);const [pending,setPending]=useState<Pending|null>(null);const [draft,setDraft]=useState<Teacher[]>([]);const [mode,setMode]=useState<'teachers'|'import'>('teachers');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const timetableInput=useRef<HTMLInputElement>(null);const teacherInput=useRef<HTMLInputElement>(null);
 async function upload(file:File|undefined,kind:Pending['kind']){if(!file)return;setError('');setBusy(true);try{const {readUpload,parseTimetable,parseTeacherWorkbook}=await import('./spreadsheet');const book=await readUpload(file);setPending(kind==='timetable'?{kind,classes:parseTimetable(book),filename:file.name}:{kind,teachers:parseTeacherWorkbook(book),filename:file.name});setMode('import');dialog.current?.showModal();}catch(e){setError(e instanceof Error?e.message:'Could not read this spreadsheet.');}finally{setBusy(false);}}
 function openTeachers(){setDraft(structuredClone(school.teachers));setError('');setMode('teachers');dialog.current?.showModal();}
 function saveTeachers(){try{const teachers=validateTeachers(draft,true);onChange({...school,teachers});dialog.current?.close();}catch(e){setError((e as Error).message);}}
 function apply(){if(!pending)return;if(pending.kind==='timetable'){onChange({...school,classes:pending.classes,selectedClass:pending.classes[school.selectedClass]?school.selectedClass:Object.keys(pending.classes)[0]});}else {const map=new Map(school.teachers.map(t=>[t.code,t]));pending.teachers.forEach(t=>map.set(t.code,t));onChange({...school,teachers:[...map.values()].sort((a,b)=>a.code.localeCompare(b.code))});}setPending(null);dialog.current?.close();}
 const missing=unknownCodes(school.classes,school.teachers);
 return <section className="data-panel" aria-label="Timetable settings"><div className="data-toolbar"><label className="class-picker">Your class<select aria-label="Your class" value={school.selectedClass} disabled={disabled||busy} onChange={e=>onChange({...school,selectedClass:e.target.value})}>{Object.keys(school.classes).map(name=><option key={name}>{name}</option>)}</select></label><div className="data-buttons"><button className="button" disabled={disabled||busy} onClick={()=>timetableInput.current?.click()}><Upload size={15}/> Upload timetable</button><button className="button" disabled={disabled||busy} onClick={()=>teacherInput.current?.click()}><Upload size={15}/> Upload teachers</button><button className="button" disabled={disabled||busy} onClick={openTeachers}><Users size={15}/> Teacher & subject list</button></div></div><input ref={timetableInput} hidden type="file" accept=".xlsx,.xls,.csv" aria-label="Timetable spreadsheet" onChange={e=>{void upload(e.target.files?.[0],'timetable');e.target.value='';}}/><input ref={teacherInput} hidden type="file" accept=".xlsx,.xls,.csv" aria-label="Teacher spreadsheet" onChange={e=>{void upload(e.target.files?.[0],'teachers');e.target.value='';}}/>
 <p className="data-caption">{busy?'Reading spreadsheet…':`${Object.keys(school.classes).length} classes · ${school.teachers.length} teacher codes · Saved on this device`}</p>{missing.length>0&&<p className="data-warning">Unmapped teacher codes: {missing.join(', ')}. Add them in the teacher list; their lessons are marked as unknown.</p>}{error&&!dialog.current?.open&&<p className="data-error" role="alert">{error}</p>}
 <dialog ref={dialog} className="data-dialog" onClose={()=>{setError('');setPending(null);}}><div className="dialog-heading"><h2>{mode==='teachers'?'Teachers & subjects':'Review spreadsheet'}</h2><button aria-label="Close data editor" onClick={()=>dialog.current?.close()}><X size={20}/></button></div>
 {mode==='teachers'?<><p className="data-description">Each code connects a timeslot to a teacher and subject. Changes apply to every class.</p><div className="teacher-actions"><button className="button" onClick={()=>setDraft([...draft,{code:'',teacher:'',subject:''}])}><Plus size={15}/> Add teacher</button><button className="button" onClick={()=>void import('./spreadsheet').then(m=>m.downloadTeachers(draft)).catch(()=>setError('Could not download the spreadsheet.'))}><Download size={15}/> Download spreadsheet</button></div><div className="teacher-table-wrap"><table className="teacher-table"><thead><tr><th scope="col">Code</th><th scope="col">Teacher</th><th scope="col">Subject</th><th scope="col"><span className="sr-only">Actions</span></th></tr></thead><tbody>{draft.map((t,i)=><tr key={i}><td><input aria-label={`Code row ${i+1}`} value={t.code} maxLength={2} inputMode="numeric" onChange={e=>setDraft(draft.map((v,j)=>j===i?{...v,code:e.target.value}:v))}/></td><td><input aria-label={`Teacher row ${i+1}`} value={t.teacher} maxLength={200} onChange={e=>setDraft(draft.map((v,j)=>j===i?{...v,teacher:e.target.value}:v))}/></td><td><input aria-label={`Subject row ${i+1}`} value={t.subject} maxLength={200} onChange={e=>setDraft(draft.map((v,j)=>j===i?{...v,subject:e.target.value}:v))}/></td><td><button className="delete-teacher" aria-label={`Remove teacher ${t.code||`row ${i+1}`}`} onClick={()=>setDraft(draft.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div></>:pending&&<><p className="data-description">{pending.filename}</p>{pending.kind==='timetable'?<><p>Found <strong>{Object.keys(pending.classes).length} classes</strong> with a full Monday–Friday timetable.</p><p className="data-description">Applying replaces all class timetables. Teacher mappings are kept.</p><div className="import-preview"><strong>Preview: {Object.keys(pending.classes)[0]}</strong>{DAYS.map((d,i)=><p key={d}><b>{d}:</b> {pending.classes[Object.keys(pending.classes)[0]][d].slice(0,i===4?8:10).map(v=>v||'—').join(' · ')}</p>)}</div>{unknownCodes(pending.classes,school.teachers).length>0&&<p className="data-warning">Unmapped codes: {unknownCodes(pending.classes,school.teachers).join(', ')}. You can add their teachers after import.</p>}</>:<><p>Found <strong>{pending.teachers.length} teacher mappings</strong>.</p><p className="data-description">Matching codes will be updated; new codes will be added. Other teachers are kept.</p><div className="import-preview">{pending.teachers.slice(0,8).map(t=><p key={t.code}><b>{t.code}</b> · {t.teacher} · {t.subject}</p>)}{pending.teachers.length>8&&<p>And {pending.teachers.length-8} more.</p>}</div></>}</>}
 {error&&<p className="data-error" role="alert">{error}</p>}<div className="dialog-footer"><button className="button" onClick={()=>dialog.current?.close()}>Cancel</button><button className="button primary" onClick={mode==='teachers'?saveTeachers:apply}>{mode==='teachers'?'Save teacher list':'Apply import'}</button></div></dialog></section>;
}
