import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { CalendarDays, Clock3, Download, Pencil, Check, Coffee, BookOpen, X, ChevronRight, Sun, CheckCircle2 } from 'lucide-react';
import { registerSW } from 'virtual:pwa-register';
import { DAYS, blankContents, parseContents, slotsFor, getStatus, formatTime, type Contents, type Slot } from './schedule';
import './style.css';
import { DataManager } from './DataManager';
import { initialSchool, restoreSchool, resolveLesson, SCHOOL_KEY, type School } from './school';
registerSW({ onRegisterError(error) { console.warn('Offline setup unavailable',error); } });
type InstallEvent = Event & {prompt(): Promise<void>;userChoice:Promise<{outcome:string}>};
const STORAGE_KEY='dayline-schedule-v1';
function App() {
 const [now,setNow]=useState(new Date());
 const [day,setDay]=useState(Math.min(4,Math.max(0,new Date().getDay()-1)));
 const [school,setSchool]=useState<School>(()=>structuredClone(initialSchool));
 const contents=school.classes[school.selectedClass];
 const [draft,setDraft]=useState<Contents>(blankContents);
 const [editing,setEditing]=useState(false);
 const [message,setMessage]=useState('');
 const [installEvent,setInstallEvent]=useState<InstallEvent|null>(null);
 const [installed,setInstalled]=useState(window.matchMedia('(display-mode: standalone)').matches);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{ try {const saved=localStorage.getItem(SCHOOL_KEY);const restored=restoreSchool(saved);if(!saved){const legacy=parseContents(localStorage.getItem(STORAGE_KEY));if(Object.values(legacy).some(slots=>slots.some(Boolean))){restored.classes['My schedule']=legacy;restored.selectedClass='My schedule';}}setSchool(restored);} catch {setMessage('Device storage is unavailable. Changes can only be kept while this app is open.');} const timer=setInterval(()=>setNow(new Date()),1000);const refresh=()=>setNow(new Date());document.addEventListener('visibilitychange',refresh);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',refresh);window.removeEventListener('focus',refresh);}; },[]);
 useEffect(()=>{const handler=(e:Event)=>{e.preventDefault();setInstallEvent(e as InstallEvent);}; const completed=()=>{setInstalled(true);setInstallEvent(null);dialog.current?.close();};window.addEventListener('beforeinstallprompt',handler);window.addEventListener('appinstalled',completed);return()=>{window.removeEventListener('beforeinstallprompt',handler);window.removeEventListener('appinstalled',completed);};},[]);
 const status=getStatus(now);
 const upcoming=getStatus(now,true);
 const todayIndex=now.getDay()-1;
 const isToday=day===todayIndex;
 const rows=slotsFor(day+1);
 const values=editing?draft:contents;
 const getLesson=(slot:Slot|null,weekday:number)=>resolveLesson(slot?.number?contents[DAYS[weekday-1]]?.[slot.number-1]||'':'',school.teachers);
 const getTitle=(slot:Slot|null,weekday:number)=>slot?.number ? getLesson(slot,weekday).subject || slot.label : slot?.label || '';
 const currentTitle=status.current ? getTitle(status.current,now.getDay()) : todayIndex<0 || todayIndex>4 ? 'Enjoy your weekend' : status.minuteNow<420 ? 'A fresh day ahead' : 'You’re done for today';
 const nextDay=upcoming.nextAt?.toLocaleDateString(undefined,{weekday:'long'});
 const sameNextDay=upcoming.nextAt?.toDateString()===now.toDateString();
 const remaining=status.current?Math.max(1,Math.ceil(status.current.end-status.minuteNow)):0;
 const progress=status.current?Math.min(100,(status.minuteNow-status.current.start)/(status.current.end-status.current.start)*100):0;
 const completed=rows.filter(s=>s.kind==='class' && isToday && s.end<=status.minuteNow).length;
 function startEdit(){setDraft(structuredClone(contents));setEditing(true);setMessage('');}
 function changeSchool(next:School){setSchool(next);try {localStorage.setItem(SCHOOL_KEY,JSON.stringify(next));setMessage('Changes saved on this device.');}catch{setMessage('Changes are kept for this session. Device storage is unavailable.');}}
 function save(){changeSchool({...school,classes:{...school.classes,[school.selectedClass]:draft}});setEditing(false);}
 async function install(){if(installEvent){await installEvent.prompt();const choice=await installEvent.userChoice;setInstallEvent(null);if(choice.outcome==='accepted')dialog.current?.close();}else dialog.current?.showModal();}
 return <div className="app-shell">
  <aside className="sidebar"><a className="brand" href="/" aria-label="Dayline home"><span className="brand-icon"><CalendarDays size={23}/></span>dayline<span className="brand-dot">.</span></a><div className="sidebar-caption">YOUR DAILY RHYTHM</div><div className="nav-active"><CalendarDays size={19}/> My schedule</div><div className="sidebar-bottom"><div className="mini-calendar"><Sun size={23}/><p>A little structure.<br/><strong>A clearer day.</strong></p></div><p className="sidebar-note">Monday – Friday<br/>One day at a time.</p></div></aside>
  <div className="main-shell"><header className="topbar"><span>My schedule <ChevronRight size={14}/> Overview</span><button className="install-button" onClick={()=>void install()} disabled={installed}><Download size={16}/>{installed?'Installed':'Install app'}</button></header>
  <main><div className="page-heading"><div><div className="eyebrow">MAKE TIME FOR YOUR DAY</div><h1>Your day, at a glance<span>.</span></h1><p>Stay in the moment. Know what’s coming next.</p></div><div className="live-clock"><div><span className="live-dot"/> LOCAL TIME</div><time>{now.toLocaleTimeString('en-GB',{hour12:false})}</time><p>{now.toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short',year:'numeric'})}</p></div></div>
  <section className="status-grid" aria-label="Current and next timeslot"><article className="current-card"><div className="card-label"><span className="current-dot"/>{status.current?'HAPPENING NOW':'RIGHT NOW'}<span className="pill">{status.current?.kind==='break'?'Break':status.current?'In progress':'Free time'}</span></div><div className="status-title"><h2>{currentTitle}</h2><span className="card-symbol">{status.current?.kind==='break'?<Coffee size={29}/>:status.current?<BookOpen size={29}/>:<Sun size={29}/>}</span></div><p className="slot-time">{status.current?`${formatTime(status.current.start)} – ${formatTime(status.current.end)}`:'Your next slot is shown beside this card.'}</p><p className="lesson-teacher">{getLesson(status.current,now.getDay()).teacher}</p><div className="current-footer">{status.current?<><div className="progress-track"><div style={{width:`${progress}%`}}/></div><div className="progress-description"><span>{status.current.number?`Timeslot ${status.current.number} of ${now.getDay()===5?8:10}`:'Take a breather'}</span><span>{remaining} min left</span></div></>:<div className="free-note"><CheckCircle2 size={16}/> Nothing scheduled right now</div>}</div></article>
  <article className="next-card"><div className="card-label"><Clock3 size={15}/> UP NEXT</div><div className="status-title"><h2>{getTitle(upcoming.next,upcoming.nextAt?.getDay()??1)}</h2><span className="next-symbol">{upcoming.next?.kind==='break'?<Coffee size={26}/>:<BookOpen size={26}/>}</span></div><p className="slot-time">{upcoming.next&&`${formatTime(upcoming.next.start)} – ${formatTime(upcoming.next.end)}`}</p><p className="lesson-teacher">{getLesson(upcoming.next,upcoming.nextAt?.getDay()??1).teacher}</p><div className="next-footer"><span>{sameNextDay?'Later today':nextDay} {upcoming.next?.number&&`· Timeslot ${upcoming.next.number}`}</span><span className="starts-in">{upcoming.nextAt&&(sameNextDay?`In ${Math.max(1,Math.ceil((upcoming.nextAt.getTime()-now.getTime())/60000))} min`:upcoming.nextAt.toLocaleDateString(undefined,{month:'short',day:'numeric'}))}</span></div></article></section>
  <DataManager school={school} onChange={changeSchool} disabled={editing}/><section className="schedule-panel"><div className="schedule-heading"><div><h2>The weekly lineup</h2><p>A place for every part of your day.</p></div><div className="edit-actions">{editing?<><button className="button quiet" onClick={()=>setEditing(false)}>Cancel</button><button className="button primary" onClick={save}><Check size={16}/> Save changes</button></>:<button className="button" onClick={startEdit}><Pencil size={15}/> Edit schedule</button>}</div></div>
  <div className="weekday-tabs" role="tablist" aria-label="Weekday">{DAYS.map((name,i)=><button key={name} id={`tab-${i}`} role="tab" tabIndex={day===i?0:-1} onKeyDown={e=>{const next=e.key==='ArrowRight'?(i+1)%5:e.key==='ArrowLeft'?(i+4)%5:e.key==='Home'?0:e.key==='End'?4:null;if(next!==null){e.preventDefault();setDay(next);document.getElementById(`tab-${next}`)?.focus();}}} aria-selected={day===i} aria-controls="day-panel" className={day===i?'selected':''} onClick={()=>setDay(i)}>{name}<span className="day-short">{name.slice(0,3)}</span>{i===todayIndex&&<span className="today-dot" aria-label="Today"/>}</button>)}</div>
  <div className="day-summary"><div><strong>{DAYS[day]}</strong><span>{day===4?'8 timeslots · Ends at 14:05':'10 timeslots · Ends at 15:15'}</span></div>{isToday?<span className="today-badge">TODAY · {completed}/{day===4?8:10} complete</span>:<span className="day-badge">{day===4?'A shorter Friday':'07:00 start'}</span>}</div>
  {editing&&<p className="edit-tip">Enter teacher codes (e.g. 02 or 02, 06) or an activity for each timeslot. Switch days to edit the whole week, then save.</p>}
  <div id="day-panel" role="tabpanel" aria-labelledby={`tab-${day}`}><div className="table-labels"><span>SLOT</span><span>TIME</span><span>SUBJECT / TEACHER</span><span>STATUS</span></div><div className="schedule-rows">{rows.map(slot=>{const active=isToday&&status.current?.id===slot.id;const past=isToday&&slot.end<=status.minuteNow;const isUpcoming=isToday&&upcoming.next?.id===slot.id&&sameNextDay;return <div key={slot.id} className={`schedule-row ${slot.kind==='break'?'break-row':''} ${active?'active-row':''} ${past?'past-row':''}`}><span className="slot-number">{slot.number?String(slot.number).padStart(2,'0'):<Coffee size={17}/>}</span><span className="row-time">{formatTime(slot.start)} <span>–</span> {formatTime(slot.end)}</span><div className="row-subject">{slot.kind==='break'?<span>{slot.label}<span className="break-description">{slot.id==='break-1'?'Recharge for 15 minutes':'Lunch & a little reset'}</span></span>:editing?<input aria-label={`${DAYS[day]} timeslot ${slot.number}`} maxLength={100} placeholder={`Code or activity for slot ${slot.number}`} value={values[DAYS[day]][slot.number!-1]} onChange={e=>{const text=e.target.value;setDraft(prev=>({...prev,[DAYS[day]]:prev[DAYS[day]].map((v,i)=>i===slot.number!-1?text:v)}));}}/>:<span className={values[DAYS[day]][slot.number!-1]?'':'empty-subject'}>{resolveLesson(values[DAYS[day]][slot.number!-1],school.teachers).subject||`Timeslot ${slot.number}`}<small className="row-teacher">{resolveLesson(values[DAYS[day]][slot.number!-1],school.teachers).teacher}</small></span>}</div><span className="row-status">{active?<span className="now-badge">Now</span>:past?<Check size={17} aria-label="Completed"/>:isUpcoming?<span className="next-badge">Next</span>:<span className="dash">—</span>}</span></div>;})}</div></div>
  <div className="end-marker"><span/><CheckCircle2 size={16}/><span>That’s the day · {day===4?'14:05':'15:15'}</span><span/></div></section>
  <footer><span><span className="footer-dot"/> Updates live with your device’s clock</span><span>Made for your Monday through Friday.</span></footer>
  <p className="feedback" role="status">{message}</p></main></div>
  <dialog ref={dialog} className="install-dialog"><div className="dialog-heading"><h2>Take Dayline with you</h2><button aria-label="Close installation instructions" onClick={()=>dialog.current?.close()}><X size={20}/></button></div><p>Install it on your home screen for quick access. Your schedule works offline after your first visit.</p><p><strong>iPhone or iPad:</strong> open in Safari, tap Share, then “Add to Home Screen”.</p><p><strong>Android or desktop:</strong> open your browser menu and choose “Install app” or “Add to Home Screen” when available.</p><p className="dialog-note">Your schedule is saved in this browser on this device.</p><button className="button primary" onClick={()=>dialog.current?.close()}>Got it</button></dialog>
 </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
